# Proxy setup
# If Polipo isn't running, you might need to start it manually after Tor.
proxy:
  host: 127.0.0.1
  # Be sure to use whatever port it is listening on (such as 8123).
  # The default port for Polipo used in the Tor Vidalia Bundle is 8118.
  port: 8123

# Twitter account info.
# Used to post most number of inmates in jail at once information.
twitter:
  API key: api_key_from_application_settings
  API secret: api_secret_from_application_settings
  Access token: access_token_from_your_access_token
  Access token secret: access_token_secret_from_your_access_token

# If the `aws` key exists, then the jail report will be saved to S3.
# aws:
#   s3:
#     region: some_region
#     bucket: some_bucket

# If the `sentry` key exists, error reporting via Sentry will be used.
# sentry:
#   dsn: some_dsn_for_your_project
